# Generated by Django 6.0.4 on 2026-06-24 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_receiptlineitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('buy_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('buy_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_holdings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ticker'],
                'unique_together': {('user', 'ticker')},
            },
        ),
    ]
