# Generated by Django 6.0.4 on 2026-06-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_stockholding'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockholding',
            name='adjusted_quantity',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Current share count after splits = quantity × split_factor', max_digits=12),
        ),
        migrations.AddField(
            model_name='stockholding',
            name='original_currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='stockholding',
            name='split_factor',
            field=models.DecimalField(decimal_places=4, default=1, help_text='Total split multiplier since buy_date. e.g. 20 for AMZN 20:1 split.', max_digits=12),
        ),
    ]
