# Generated by Django 6.0.4 on 2026-06-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_stockholding_adjusted_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockholding',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='stockholding',
            name='adjusted_quantity',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockholding',
            name='buy_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='stockholding',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='stockholding',
            name='quantity',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockholding',
            name='split_factor',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=12),
        ),
    ]
